# This is a config for E2B sandbox template.
# You can use template ID (eqgu27ctz3fim25sejxa) or template name (vibe-nextjs-demo-1753197807) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-demo-1753197807") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-demo-1753197807") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-demo-1753197807')

team_id = "e8e7099a-e03a-43f0-af9f-30835a7cde1d"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-demo-1753197807"
template_id = "eqgu27ctz3fim25sejxa"
